### ISSUE TITLE
Range check problem

### ISSUE THREAD

**Issue by soberl** [rems-project/sail-riscv#72] opened 2020-10-29 02:02 UTC
https://github.com/rems-project/sail-riscv/blob/ae6cb1de092e9ea727e2318d76e9b88999bbee59/model/riscv_pmp_control.sail#L60

I think it should be "if      (addr + width <_u lo) | (hi <=_u addr)" instead.
Suppose there are 2 ranges: [0x0, 0x200000) and [0x200000, 0x300000). Giving an address 0x200000 with any size, it should be belong to the 2nd range.

**Comment by allenjbaum** [comment] 2021-02-26 01:50
This appears to be correct - 
ranges for PMP NAPOT format define regions at base..base+regionsize-1
ranges for PMP range    format define regions at base_lo..base_hi-1
This is a bug in the RISC-V Sail model

**Comment by scottj97** [comment] 2021-02-26 05:10
It's broken on the low end, too. With your example ranges, consider an access to addr=0x1ffffc width=4. This is outside of the second range, yet `(addr + width <_u lo)` would incorrectly say that it's within that entry.

Correct:
```
                        if      (addr + width <=_u lo) | (hi <=_u addr)
```

**Comment by soberl** [comment] 2021-02-26 05:46
Yes.
For easier understanding, maybe (assert width > 0):
`if      (addr >= _u hi) | (addr + width <=_u lo) `

**Comment by scottj97** [comment] 2021-02-27 00:12
I wonder if there's similar corner cases here when accessing the largest-addressed bytes in memory. addr=0xFFFFFFFC width=4, so addr+width wraps around.

Since addr is of type `xlenbits`, this would apply only to RV32, since RV64 physical addresses can't be so large as to wrap. (Right?)

**Comment by soberl** [comment] 2021-05-06 15:50
See the fix as commented.

**Comment by scottj97** [comment] 2021-05-06 16:05
@soberl what fix? What comment? #85 is still open?

**Comment by soberl** [comment] 2021-05-06 23:54
Ah, yes, it's still open. Let me reopen this issue.

> @soberl what fix? What comment? #85 is still open?

**Comment by rmn30** [comment] 2021-07-23 12:58
I believe this is fixed by https://github.com/rems-project/sail-riscv/pull/85 but someone should check.

**Comment by scottj97** [comment] 2021-07-23 15:26
I can confirm it is fixed.

**Closed** 2021-07-23 15:51 UTC
